# Generated by Django 6.0.4 on 2026-04-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='best_season_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='best_season_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
