# Generated by Django 6.0.4 on 2026-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_best_season_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='capacity_per_day',
            field=models.IntegerField(default=20),
        ),
    ]
