# Generated by Django 6.0.1 on 2026-01-13 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='destination_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='num_persons',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='destinations.destination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_screenshot',
            field=models.ImageField(default=0, upload_to='payments/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='persons',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
